# pull official base image
FROM node:13.12.0-alpine

WORKDIR /app

# add `/app/node_modules/.bin` to $PATH
ENV PATH /app/node_modules/.bin:$PATH

#Copy package.json to container
COPY package.json ./
COPY package-lock.json ./

#Install dependencies for app
RUN npm install 
RUN npm install react-scripts@3.4.1 -g

# add app
COPY . ./

# start app
CMD ["npm", "start"]
