# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: TimecodeCalculator CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Login to DockerHub Registry
      run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
      
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies 
      run: npm ci
    
    - name: Run tests
      run: npm test

    - name: Get the version
      id: vars
      run: echo ::set-output name=tag::$(echo ${GITHUB_REF:11})


    - name: Build tagged Docker image
      run: docker build . --file Dockerfile --tag oskarfranzen/timecode_calculator:${{steps.vars.outputs.tag}}

    - name: Push tagged Docker image
      run: docker push oskarfranzen/timecode_calculator:${{steps.vars.outputs.tag}}

    - name: Build latest Docker image
      run: docker build . --file Dockerfile --tag oskarfranzen/timecode_calculator:latest
        
    - name: Push latest Docker image
      run: docker push oskarfranzen/timecode_calculator:latest
    
